[package]
name = "wasm-demo"
version = "0.1.0"
authors = ["Hao Hou <haohou302@gmail.com>"]
edition = "2018"

[lib]
crate-type=['cdylib']

[dependencies]
plotters = {path = "../.."}
wasm-bindgen = "0.2.43"
wee_alloc = "*"

[profile.release]
opt-level = 'z'
lto = true
