name: Publish GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: 'latest'
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '10'
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build with wasm-pack
        run: wasm-pack build --release --target web
      - name: npm install
        working-directory: ./www
        run: npm install
      - name: npm build
        working-directory: ./www
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: www/dist

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
